// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/consumer/start": {
            "post": {
                "description": "Publishes a job message to RabbitMQ with connection parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consume"
                ],
                "summary": "Consume a job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RabbitMQ host",
                        "name": "host",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RabbitMQ port",
                        "name": "port",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RabbitMQ user",
                        "name": "user",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RabbitMQ password",
                        "name": "password",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RabbitMQ queue",
                        "name": "queue",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Consumer success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Error response",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Verifica se a API está ativa",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ping"
                ],
                "summary": "Ping endpoint",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/publish": {
            "post": {
                "description": "Publishes a job message to RabbitMQ with connection parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Publish"
                ],
                "summary": "Publish a job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RabbitMQ host",
                        "name": "host",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RabbitMQ port",
                        "name": "port",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RabbitMQ user",
                        "name": "user",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RabbitMQ password",
                        "name": "password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Job object to publish",
                        "name": "job",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Job"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Publish success response",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Error response",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Job": {
            "type": "object",
            "required": [
                "date",
                "description",
                "name",
                "priority"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AgentApiGo",
	Description:      "This is a sample API to demonstrate Swagger with Gin.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
